### ISSUE TITLE
Syntax highlighting in slang exampls sometimes looks bad

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/docs#1]
In Cloudslang code examples, the syntax highlighting does not always look good. for example:
![image](https://cloud.githubusercontent.com/assets/7547370/9059842/7a8dfea8-3ab6-11e5-9f56-60a2efcb80a4.png)

**Comment by SamMarkowitz** [comment]
There's not much we can do about the highlighting. We've marked the snippet as YAML code, but it doesn't even know what to do with that.

It's probably technically possible to tag up every line of code ourselves, but not practically feasible. 

Same problem in the old docs:
![image](https://cloud.githubusercontent.com/assets/9436355/9060268/dadfb0ea-3aba-11e5-9dd2-6a240d2a54ab.png)

**Comment by orius123** [comment]
So.. 
To close it?

**Comment by SamMarkowitz** [comment]
I don't know what else can be done at this point.
