### ISSUE TITLE
Update Versions

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/docs#10]
Do the versions found here
- http://cloudslang-docs.readthedocs.org/en/v0.8/developer_cloudslang/#embedded-cloudslang
- http://cloudslang-docs.readthedocs.org/en/v0.8/developer_score/#embed-score-in-a-java-application

need to be updated?

To what?

**Comment by meirwah** [comment]
score : 0.2.2
cloudslang : 0.8.0.1

**Comment by orius123** [comment]
Why not to use the "official" 0.8 and 0.2?

**Comment by meirwah** [comment]
there is a small engine fix in 0.2.1...
and 0.8.0.1 includes it...

but we can go also with "official" 0.8 and 0.2...

**Comment by orius123** [comment]
I don't think this fix affects clang users so much.

**Comment by SamMarkowitz** [comment]
Have we settled on the "official versions" then?

**Comment by meirwah** [comment]
@SamMarkowitz  that's fine, go with official..
