### ISSUE TITLE
Python requirements

### ISSUE THREAD

**Issue by mbettan** [CloudSlang/docs#110]
Hello,

Python is today a must have requirement for using CloudSlang, many content are based on Python operations, so it's pre-requisite 

http://cloudslang-docs.readthedocs.org/en/latest/cloudslang_cli.html

CloudSlang website (and also releases notes) don't show Python library as a pre-requisite, we should add this and also prevent user to not use any Jython which is not compatible.

We should also talk about pip install -r requirements.txt which is also required

Installing packages into the python-lib folder:

Prerequisite: pip - see pip's documentation for how to install.

Edit the requirements.txt file in the python-lib folder, which is found at the same level as the bin folder that contains the CLI executable.
Enter the Python package and all its dependencies in the requirements file.
See the pip documentation for information on how to format the requirements file.
Run the following command from inside the python-lib folder: bash pip install -r requirements.txt -t .  Note: If your machine is behind a proxy you will need to specify the proxy using pip's --proxy flag.
Note: If you have defined a JYTHONPATH environment variable, you will need to add the python-lib folder's path to its value.

**Comment by SamMarkowitz** [comment]
I'm not sure I agree with adding Python as a general requirement for CloudSlang on the website. Other than that, I am creating a couple of PR's to add more information to the docs and readme of the content repository. I think that should cover our bases.
