### ISSUE TITLE
Docker image Dev & PROD

### ISSUE THREAD

**Issue by mbettan** [CloudSlang/docs#119]
Hello

Docker DEV image is now commit : https://github.com/CloudSlang/CloudSlang-Docker-Image/blob/master/0.9.1/dev/

Docker image: https://hub.docker.com/r/cloudslang/cloudslang-dev/

It's important now to update the website, to allow new users to start working with Docker dev platform VERY quickly. In my opinion, Docker PROD image should not be the way to go for a quick start & try described on http://www.cloudslang.io/#/getstarted#top

Could we improve this on the website ?

Thanks

**Comment by levice14** [comment]
@mbettan , could you supply a short description for the image / usage examples / why is it better for a first time user to go with DEV?

also adding @SamMarkowitz

**Comment by mbettan** [comment]
Description - This Docker image provides readymade CloudSlang 0.9.1 platform with all prerequistes for a new developpers to quickly start developping his first workflows with CloudSlang. It provides Python, Git client, Atom with plugin and X11 environment.

Use Cases - A new CloudSlang user can easy try and develop his first workflows using this docker image.

We should change description for PROD docker image, which is for me not useful to quickly try Docker. There is no value for a new user to do a echo "hello world"
