### ISSUE TITLE
Mentioning the escaping of !default in Linux for cslang-builder

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/docs#12]
I was trying to run the cslang-builder on linux with a test suite like:
`<path>/cslang-builder -ts !default,rft`
and received:
`-bash: !default,rft: event not found`

I felt that it was worth documenting that on linux the "!" should be escaped for it to work since the error message is not clear enough in my opinion.

@SamMarkowitz what do you think?

**Comment by SamMarkowitz** [comment]
Sure. Can you show me an example of how the escaping looks?

**Comment by tudorlesan** [comment]
`<path>/cslang-builder -ts \!default,rft`

So it's only the "!" that's causing problems.

**Comment by levice14** [comment]
please check if it happens on any `linux` distribution or just specific one and document that accordingly

**Comment by tudorlesan** [comment]
As the exclamation mark is part of history expansion in bash it it should either be enclosed by quotes or  escaped with "\". There might be versions of shell that work with "!" but I don't think it's worth documenting every version depending on which one allows "!" and which doesn't. Personally I think it's easier just to suggest that for Linux distributions "!" should be escaped with "\"
