### ISSUE TITLE
Tutoriel - Specify requirements for running Python actions

### ISSUE THREAD

**Issue by mbettan** [CloudSlang/docs#15]
Hello,

It would be good to improve the documentation for adding Python current limitation on CloudSlang platform.
Cython not supported
Python 3 not supported
How to check if you run a Cython dependency library

" we are supporting Python 2.7 (no 3), and we have a limitation that we do not support Python libs that need CPython (It's a Jython limitation actually)...
Need to check if your libs are using CPython..."

**Comment by SamMarkowitz** [comment]
Yes. I will add to docs and maybe the tutorial as well.

Currently the docs only mention the version limitation (http://cloudslang-docs.readthedocs.org/en/v0.8/cloudslang_dsl_reference/#python_script).
