### ISSUE TITLE
Document supported chars in input / output names

### ISSUE THREAD

**Issue by levice14** [CloudSlang/docs#212]
"It will probably be a strict set like [\w] since it needs to be aligned with Java, Python (they are usually translated as variable names), Yaml and CS standards (they need to “look good”)."

**Comment by SamMarkowitz** [comment]
@Bonczidai, this is what we currently have in the docs. Does something need fixing or tweaking? Once we get the details correct I will add references to it in relevant sections.

"Variable names in CloudSlang files cannot contain localized characters. In general, CloudSlang variable names must conform to both Python’s naming constraints as well as Java’s naming constraints."

**Comment by levice14** [comment]
I think that looks good :+1:
