### ISSUE TITLE
Missing supported keywords in documentation

### ISSUE THREAD

**Issue by DorinelUtiu** [CloudSlang/docs#259]
It should be very helpful to have all the cloud slang supported keywords. Also with the section where they can be used.

**Comment by SamMarkowitz** [comment]
@DorinelUtiu can you please clarify what you think is missing from the docs.

We have this section: http://cloudslang-docs.readthedocs.io/en/latest/cloudslang_dsl_reference.html#keywords-a-z which lists all the keywords.

And we have this section: http://cloudslang-docs.readthedocs.io/en/latest/cloudslang_dsl_reference.html#structure that shows were the keywords can be used.

**Comment by SamMarkowitz** [comment]
@DorinelUtiu can you please advise if you think we need to add anything?

**Comment by andreivasiletruta** [comment]
closed as no plans to implement besides the current supported documentation on keywords
