### ISSUE TITLE
Document validation cases

### ISSUE THREAD

**Issue by levice14** [CloudSlang/docs#260]
https://github.com/CloudSlang/cloud-slang/issues/817

we decided to enhance documentation on the first two cases:

```
- I think that since name: true or name: 3 fails compilation, we should document it as illegal names
- Regarding the reserved words for which we cannot create folders or files, do we want to document them as illegal?
```

IMHO this list should also mention reserved keywords of Java and Python

**Comment by SamMarkowitz** [comment]
@oritstone, @Bonczidai what are the reserved words which we don't allow for folders and files?

**Comment by levice14** [comment]
the ones that are reserved / invalid for the operating systems we support (Windows, Linux) in case of folders / files
java and python keywords for variable names (inputs / outputs ..)

@oritstone do you think it worth document these explicitly?

**Comment by oritstone** [comment]
In executable names, if the name is interpreted as a value with type other than string. 
For example in `name: true` the value will be interpreted as boolean
In `name: 3` the value will be treated as number. 
Those cases will fail compilation so I think we should mention them

In case of reserved words for executable name or namespace, Windows does not allow to create folders or files with one of the following names:
'CON', 'PRN', 'AUX', 'CLOCK$', 'COM1', 'COM2', 'COM3', 'COM4', 'COM5', 'COM6', 'COM7', 'COM8', 'COM9', 'NUL', 'LPT1', 'LPT2', 'LPT3', 'LPT4', 'LPT5', 'LPT6', 'LPT7', 'LPT8', 'LPT9'
I'm not sure if we should mention them specifically...
