### ISSUE TITLE
Perhaps adding short examples to the most frequent error messages (indentation, missing keys like do )

### ISSUE THREAD

**Issue by andreivasiletruta** [CloudSlang/docs#278]
_From @meshipeer on April 6, 2015 7:41_

@SSgtMendel raised this during bug hunt

_Copied from original issue: CloudSlang/CloudSlang.github.io#71_

**Comment by tethryus** [comment]
@andreivasiletruta I would consider that this issue can be closed, since the plugin catches all related errors and the user will know by the error message provided.
