### ISSUE TITLE
Tutorial Lesson 5: check_address step needs "navigate" clause...

### ISSUE THREAD

**Issue by domhnallw** [CloudSlang/docs#280]
Hi:

While walking through the tutorial, I discovered that I couldn't run the code I'd written (which was identical to the "New Code - Complete" provided), as I was getting the following error:

```
Command failed java.lang.RuntimeException: java.lang.RuntimeException: Failed to compile step: check_address. The step/result name: FAILURE of navigation: FAILURE -> FAILURE is missing
```

Anyway, adding the following to the end of the `check_address` solved the problem:

```
navigate:
  - SUCCESS: print_finish
  - FAILURE: print_finish
```

I'm using Cloudslang 1.0.0 here.

**Comment by domhnallw** [comment]
I know this is somewhat addressed in the next step, but the flow won't compile as it currently stands, which I reckon either means:

1. The example is slightly wrong/old, or
2. You have to tell the reader that the code in its current state won't compile.

**Comment by andreivasiletruta** [comment]
@domhnallw I checked the tutorial and it worked for me. maybe I am missing something.
let's try to get in touch so that I understand better.

**Comment by SamMarkowitz** [comment]
The tutorial code folder gets verified using the Build Tool like everything else. 

Right now the master version of the tutorial looks like its being built by an old version (https://github.com/CloudSlang/docs/blob/master/circle.yml#L17), so there is a chance it doesn't compile against 1.0.0. The v1.0 branch of the tutorial is running against the right Build Tool version.

There's also always the possibility that the code folder and the code in the tutorial text are not the same.

**Comment by andreivasiletruta** [comment]
@domhnallw when you walk through the tutorial on read the docs what are you reading?
latest? 1.0? something else?
http://cloudslang-docs.readthedocs.io/en/latest/ or http://cloudslang-docs.readthedocs.io/en/v1.0/ or others
