### ISSUE TITLE
Tutorial Lesson #11 uses contains.sl not defined until Lesson #12

### ISSUE THREAD

**Issue by domhnallw** [CloudSlang/docs#282]
The code example provided for Lesson 11 includes a reference to `base/contains.sl` which is only defined in Lesson 12. Yields the following error:

```
Command failed java.lang.RuntimeException: java.lang.RuntimeException: Reference: 'tutorials.base.contains' in executable: 'new_hire', wasn't found in path
```

**Comment by andreivasiletruta** [comment]
@domhnallw  you are right. the new_hire from the tutorial mentions base.contains. This should be changed. 

The good thing is that the downloadable code does not contain same reference.
