### ISSUE TITLE
Move top level documentation files into a directory

### ISSUE THREAD

**Issue by levice14** [CloudSlang/docs#288]
IMHO it would be nice ti move the the top level documentation files into folder structure for better readability and maintainability of the repo

so top root folder will contain only files like README, circle.yml ..

@andreivasiletruta WDYT?

**Comment by SamMarkowitz** [comment]
Yes, it should have been like that in the first place. Completely my fault. It used to have to be flat, but when we changed to restructuredText I could have put the top level stuff into folders.

The reason we didn't fix it later is because switching versions on a specific page would break.

**Comment by levice14** [comment]
👍 thanks @SamMarkowitz - I think it is worth to do a little experimentation with it to see whether the problems still persist

**Comment by andreivasiletruta** [comment]
@Bonczidai you are right. it should be moved and checked.
