### ISSUE TITLE
Code in New Code - Complete in Lesson 5 fails

### ISSUE THREAD

**Issue by stefan-bergstein** [CloudSlang/docs#300]
Example 5 fails with:
SEVERE: Command failed java.lang.RuntimeException: Failed compilation for file : new_hire.sl ,Exception is : java.lang.RuntimeException: Step 'print_finish' is unreachable.

The Step check_address contains a navigate that is not correct.

        navigate:
          - SUCCESS: SUCCESS

The code in the zip file is correct, but not the code on the web page.

**Comment by tethryus** [comment]
Hello @stefan-bergstein
Thank you for catching this issue. There is a PR which contains the fix for the flow which failed to compile.
It will be reviewed and merged as soon as possible.
