### ISSUE TITLE
Move v0.8 to Sphinx

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/docs#42]

**Comment by oritstone** [comment]
Until then the link from the docs to the docs of 0.8 will not work...
The user will need to access the version docs directly

**Comment by SamMarkowitz** [comment]
Actually, right now it's the opposite. The website points to the 0.8 docs (to be in sync with the 0.8 CLI that it also points to). Switching to the latest docs will not work now.

Once 0.9 is released the docs will point there and switching to the latest (master) docs will work, but switching to 0.8 will not.
