### ISSUE TITLE
Remove from docs the reference to Sublime plugin

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/docs#54]

**Comment by SamMarkowitz** [comment]
Are we sure we don't want to just leave it for people who prefer Sublime? I already added a comment saying it is no longer being actively developed.

**Comment by oritstone** [comment]
We do not plan to continue to support it, now that we have the Atom integration
I already do not know if it is still working...
Do you think it is better to leave it in the docs without supporting it? 
@meshipeer @meirwah @orius123 @SamMarkowitz @Bonczidai, WDYT?

**Comment by SamMarkowitz** [comment]
Now that I think about it a bit more, it will be just another thing for us to think about every time we make a DSL change and eventually will probably not work right because of DSL changes.

**Comment by orius123** [comment]
I'm for dropping it.
If there will be some community section we can add it there.
