### ISSUE TITLE
Remove the one-liner task syntax from docs & tutorials

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/docs#55]

**Comment by oritstone** [comment]
Depends on the language change: https://github.com/CloudSlang/cloud-slang/issues/492

**Comment by SamMarkowitz** [comment]
I don't see any harm in removing it before CloudSlang/cloud-slang#492 if we happen to get to it here first. It was only a syntactic shortcut to begin with.

**Comment by oritstone** [comment]
Agree @SamMarkowitz
